server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /logs/nginx/access.log
    pipeline_stages:
      - json:
          expressions:
            time_local: time_local
            remote_addr: remote_addr
            remote_user: remote_user
            request: request
            request_method: request_method
            request_uri: request_uri
            status: status
            body_bytes_sent: body_bytes_sent
            request_time: request_time
            http_referer: http_referer
            http_user_agent: http_user_agent
            http_x_forwarded_for: http_x_forwarded_for
            upstream_response_time: upstream_response_time
            upstream_addr: upstream_addr
            upstream_status: upstream_status
      - labels:
          status:
          request_method:
          upstream_status:
      - timestamp:
          source: time_local
          format: 02/Jan/2006:15:04:05 -0700

  - job_name: nginx-error
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-error
          __path__: /logs/nginx/error.log
