name: Ruff Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: gustavopajuelo/python3.12.11:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dummy steps
        run: echo 'pruebita'

      - name: Install dev dependencies
        run: uv sync --only-group dev

      - name: Run ruff
        run: ruff .
