name: Ruff Lint

on:
  pull_request:

jobs:
  ruff-check:
    runs-on: ubuntu-latest
    container:
      image: gustavopajuelo/python3.12.11:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dev dependencies
        run: uv sync --only-group dev

      - name: Run ruff check
        run: uv run ruff check

  ruff-format:
    runs-on: ubuntu-latest
    container:
      image: gustavopajuelo/python3.12.11:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dev dependencies
        run: uv sync --only-group dev

      - name: Run ruff format --check
        run: uv run ruff format --check
